'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ROP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 18113000.0.
        '''</summary>
        Friend ReadOnly Property cuartoLimiteRentaIndependiente() As String
            Get
                Return ResourceManager.GetString("cuartoLimiteRentaIndependiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.1.
        '''</summary>
        Friend ReadOnly Property cuartoTramoRentaIndependiente() As String
            Get
                Return ResourceManager.GetString("cuartoTramoRentaIndependiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.1.
        '''</summary>
        Friend ReadOnly Property porcentajeLimiteSalario() As String
            Get
                Return ResourceManager.GetString("porcentajeLimiteSalario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 817000.0.
        '''</summary>
        Friend ReadOnly Property primerLimiteRentaAsalariado() As String
            Get
                Return ResourceManager.GetString("primerLimiteRentaAsalariado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 3628000.0.
        '''</summary>
        Friend ReadOnly Property primerLimiteRentaIndependiente() As String
            Get
                Return ResourceManager.GetString("primerLimiteRentaIndependiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.055.
        '''</summary>
        Friend ReadOnly Property primerPorcentajeCargaSocial() As String
            Get
                Return ResourceManager.GetString("primerPorcentajeCargaSocial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.15.
        '''</summary>
        Friend ReadOnly Property primerTramoRentaAsalariado() As String
            Get
                Return ResourceManager.GetString("primerTramoRentaAsalariado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.25.
        '''</summary>
        Friend ReadOnly Property primerTramoRentaIndependiente() As String
            Get
                Return ResourceManager.GetString("primerTramoRentaIndependiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.
        '''</summary>
        Friend ReadOnly Property quintoTramoRentaIndependiente() As String
            Get
                Return ResourceManager.GetString("quintoTramoRentaIndependiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 1226000.0.
        '''</summary>
        Friend ReadOnly Property segundoLimiteRentaAsalariado() As String
            Get
                Return ResourceManager.GetString("segundoLimiteRentaAsalariado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 5418000.0.
        '''</summary>
        Friend ReadOnly Property segundoLimiteRentaIndependiente() As String
            Get
                Return ResourceManager.GetString("segundoLimiteRentaIndependiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.0334.
        '''</summary>
        Friend ReadOnly Property segundoPorcentajeCargaSocial() As String
            Get
                Return ResourceManager.GetString("segundoPorcentajeCargaSocial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.1.
        '''</summary>
        Friend ReadOnly Property segundoTramoRentaAsalariado() As String
            Get
                Return ResourceManager.GetString("segundoTramoRentaAsalariado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.20.
        '''</summary>
        Friend ReadOnly Property segundoTramoRentaIndependiente() As String
            Get
                Return ResourceManager.GetString("segundoTramoRentaIndependiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 9038000.0.
        '''</summary>
        Friend ReadOnly Property tercerLimiteRentaIndependiente() As String
            Get
                Return ResourceManager.GetString("tercerLimiteRentaIndependiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.
        '''</summary>
        Friend ReadOnly Property tercerTramoRentaAsalariado() As String
            Get
                Return ResourceManager.GetString("tercerTramoRentaAsalariado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.15.
        '''</summary>
        Friend ReadOnly Property tercerTramoRentaIndependiente() As String
            Get
                Return ResourceManager.GetString("tercerTramoRentaIndependiente", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
