'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IncentivoFiscal
    
    '''<summary>
    '''menuContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''campoTextoSalario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents campoTextoSalario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''campoTextoAporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents campoTextoAporte As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''botonCalcular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botonCalcular As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''botonLimpiar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents botonLimpiar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''primeraEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents primeraEtiqueta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''segundaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents segundaEtiqueta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''terceraEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents terceraEtiqueta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cuartaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cuartaEtiqueta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''quintaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quintaEtiqueta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''sextaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sextaEtiqueta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''septimaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents septimaEtiqueta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''octavaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents octavaEtiqueta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''novenaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents novenaEtiqueta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''decimaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents decimaEtiqueta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''undecimaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents undecimaEtiqueta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''duodecimaEtiqueta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents duodecimaEtiqueta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaDoce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaDoce As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaTrece control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaTrece As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaCatorce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaCatorce As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaQuince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaQuince As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''etiquetaDieciseis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaDieciseis As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaDiecisiete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaDiecisiete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''etiquetaDieciocho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaDieciocho As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaDiecinueve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaDiecinueve As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaVeinte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeinte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaVeintiuno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeintiuno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaVeintidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeintidos As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''etiquetaVeintitres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeintitres As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaVeinticuatro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeinticuatro As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''etiquetaFaltante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaFaltante As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaVeinticinco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeinticinco As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaVeintiseis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeintiseis As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''etiquetaVeintisiete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeintisiete As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaVeintiocho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeintiocho As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''etiquetaVeintinueve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaVeintinueve As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaTreinta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaTreinta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaTreintaiuno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaTreintaiuno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaTreintaidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaTreintaidos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''etiquetaTreintaitres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etiquetaTreintaitres As Global.System.Web.UI.WebControls.Label
End Class
